import type { Metadata } from "next";
import { Belanosima } from "next/font/google";
import "./globals.css";
import { CoinsProvider } from "../context/CoinsContext";

const belanosima = Belanosima({
  variable: "--font-belanosima",
  subsets: ["latin"],
  weight: ["400", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${belanosima.variable} antialiased`} style={{ fontFamily: 'var(--font-belanosima), sans-serif' }}>
        <CoinsProvider>{children}</CoinsProvider>
      </body>
    </html>
  );
}
